// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://lopwawyfmzvekrhvzply.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvcHdhd3lmbXp2ZWtyaHZ6cGx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTE5MjIsImV4cCI6MjA3MTY2NzkyMn0.MqG5n2HStfr97nh7L3YY3n9y1XDqJnNf7-FOsEa6yyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    storageKey: 'sb-lopwawyfmzvekrhvzply-auth-token',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'clarifi-app'
    }
  }
});